using System.Text;
using MathLLMBackend.Core.Configuration;
using MathLLMBackend.Core.Constants;
using MathLLMBackend.Domain.Entities;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace MathLLMBackend.Core.Services.LlmService;

public class LlmLoggingService : ILlmLoggingService
{
    private readonly ILogger<LlmLoggingService> _logger;
    private readonly LlmLoggingConfiguration _config;
    
    public LlmLoggingService(
        ILogger<LlmLoggingService> logger,
        IOptions<LlmLoggingConfiguration> config)
    {
        _logger = logger;
        _config = config.Value;
    }
    
    public async Task LogInteraction(int taskType, IEnumerable<Message> messages, string response, string modelName)
    {
        if (!_config.Enabled)
        {
            return;
        }
        
        try
        {
            var sb = new StringBuilder();
            sb.AppendLine($"==== LLM INTERACTION LOG - {DateTime.Now:yyyy-MM-dd HH:mm:ss} ====");
            sb.AppendLine($"Task Type: {GetTaskTypeName(taskType)} (Code: {taskType})");
            sb.AppendLine($"Model: {modelName}");
            sb.AppendLine("\n--- MESSAGES SENT TO LLM ---");
            
            foreach (var message in messages)
            {
                sb.AppendLine($"[{message.MessageType}] {(message.IsSystemPrompt ? "(SYSTEM PROMPT)" : "")}");
                sb.AppendLine(message.Text);
                sb.AppendLine("-----------------------------");
            }
            
            sb.AppendLine("\n--- LLM RESPONSE ---");
            sb.AppendLine(response);
            sb.AppendLine("=============================================\n\n");
            
            _logger.LogInformation("LLM INTERACTION:\n{InteractionLog}", sb.ToString());
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to log LLM interaction");
        }
    }
    
    public async Task LogSolution(string problem, string solution, string modelName)
    {
        if (!_config.Enabled)
        {
            return;
        }
        
        try
        {
            var sb = new StringBuilder();
            sb.AppendLine($"==== LLM SOLUTION LOG - {DateTime.Now:yyyy-MM-dd HH:mm:ss} ====");
            sb.AppendLine($"Model: {modelName}");
            sb.AppendLine("\n--- PROBLEM ---");
            sb.AppendLine(problem);
            sb.AppendLine("\n--- SOLUTION GENERATED BY LLM ---");
            sb.AppendLine(solution);
            sb.AppendLine("=============================================");
            
            _logger.LogInformation("LLM SOLUTION:\n{SolutionLog}", sb.ToString());
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to log LLM solution");
        }
    }
    
    private static string GetTaskTypeName(int taskType)
    {
        return taskType switch
        {
            TaskTypes.Default => "Default (Tutor)",
            TaskTypes.Learning => "Learning",
            TaskTypes.Guided => "Guided",
            TaskTypes.Exam => "Exam",
            _ => $"Unknown ({taskType})"
        };
    }
}