using System.Text;
using MathLLMBackend.Core.Configuration;
using MathLLMBackend.Core.Constants;
using MathLLMBackend.Domain.Entities;
using Microsoft.Extensions.Logging;

namespace MathLLMBackend.Core.Services.LlmService;

internal static class LlmLoggerExtensions
{
    public static void LogLlmInteraction(this ILogger logger, int taskType, IEnumerable<Message> messages, string response, string modelName)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"==== LLM INTERACTION LOG - {DateTime.Now:yyyy-MM-dd HH:mm:ss} ====");
        sb.AppendLine($"Task Type: {GetTaskTypeName(taskType)} (Code: {taskType})");
        sb.AppendLine($"Model: {modelName}");
        sb.AppendLine("\n--- MESSAGES SENT TO LLM ---");
        
        foreach (var message in messages)
        {
            sb.AppendLine($"[{message.MessageType}] {(message.IsSystemPrompt ? "(SYSTEM PROMPT)" : "")}");
            sb.AppendLine(message.Text);
            sb.AppendLine("-----------------------------");
        }
        
        sb.AppendLine("\n--- LLM RESPONSE ---");
        sb.AppendLine(response);
        sb.AppendLine("=============================================\n\n");
        
        logger.LogInformation("LLM INTERACTION:\n{InteractionLog}", sb.ToString());
    }
    
    public static void LogLlmSolution(this ILogger logger, string problem, string solution, string modelName)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"==== LLM SOLUTION LOG - {DateTime.Now:yyyy-MM-dd HH:mm:ss} ====");
        sb.AppendLine($"Model: {modelName}");
        sb.AppendLine("\n--- PROBLEM ---");
        sb.AppendLine(problem);
        sb.AppendLine("\n--- SOLUTION GENERATED BY LLM ---");
        sb.AppendLine(solution);
        sb.AppendLine("=============================================");
        
        logger.LogInformation("LLM SOLUTION:\n{SolutionLog}", sb.ToString());
    }
    
    private static string GetTaskTypeName(int taskType)
    {
        return taskType switch
        {
            TaskTypes.Default => "Default (Tutor)",
            TaskTypes.Learning => "Learning",
            TaskTypes.Guided => "Guided",
            TaskTypes.Exam => "Exam",
            _ => $"Unknown ({taskType})"
        };
    }
}